version: "3.8"

services:
  csenv:
    image: ghcr.io/mossuru777/docker-csenv-for-dev/csenv-for-dev-apache:latest
    hostname: csenv.test
    ports:
      - "80:80"     # Apache
      - "7765:7765" # Perl Remote Debug (Camelcadedb)
#    volumes:
#      - type: bind
#        source: "/foo/bar
#        target: "/var/www/html"

    environment:
      PERL5_DEBUG_ROLE: "server"
      PERL5_DEBUG_HOST: "0.0.0.0"
      PERL5_DEBUG_PORT: "7765"
      SMTP_HOSTNAME: "maildev.test"

  maildev:
    image: maildev/maildev
    hostname: maildev.test
    ports:
      - "1080:80"
    environment:
      MAILDEV_PORT_25_TCP_PORT: "25"
