name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build_and_push:
    name: Build and Push
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and Push csenv-for-dev:apache-latest (csenv-for-dev-apache)
        uses: docker/build-push-action@v2
        with:
          context: .
          target: csenv-for-dev-apache
          push: true
          tags: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/csenv-for-dev:apache-latest
          cache-from: type=gha
          cache-to: type=gha

      - name: Build and Push csenv-for-dev:latest (csenv-for-dev)
        uses: docker/build-push-action@v2
        with:
          context: .
          target: csenv-for-dev
          push: true
          tags: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/csenv-for-dev:latest
          cache-from: type=gha
