name: Build Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-images:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get Lowercase Repository Name
        run: |
          echo "LOWER_REPOITORY_NAME=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: csenv-for-dev
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ env.LOWER_REPOITORY_NAME }}/csenv-for-dev:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
