name: Build and Push Docker Image

on:
  push:
    branches:
      - main
  repository_dispatch:
    types:
      - upstream-update
      - dependencies-update
  workflow_dispatch:

jobs:
  build_and_push:
    name: Build and Push
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Fetch Devel::Camelcadedb Latest Version
        id: fetch-devel-camelcadedb-latest-version
        uses: ./.github/actions/fetch-devel-camelcadedb-lastest-version

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PERSONAL_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and Push csenv-for-dev:apache-latest (csenv-for-dev-apache)
        uses: docker/build-push-action@v3
        with:
          context: .
          target: csenv-for-dev-apache
          push: true
          tags: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/csenv-for-dev:apache-latest
            ${{ secrets.DOCKER_HUB_USERNAME }}/csenv-for-dev:apache-${{ steps.fetch-devel-camelcadedb-latest-version.outputs.version }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build and Push csenv-for-dev:latest (csenv-for-dev)
        uses: docker/build-push-action@v2
        with:
          context: .
          target: csenv-for-dev
          push: true
          tags: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/csenv-for-dev:latest
            ${{ secrets.DOCKER_HUB_USERNAME }}/csenv-for-dev:${{ steps.fetch-devel-camelcadedb-latest-version.outputs.version }}
          cache-from: type=gha
